from __future__ import annotations

import math
import os

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
HALF_HEIGHT = SCREEN_HEIGHT // 2
INTERNAL_RENDER_WIDTH = 640
INTERNAL_RENDER_HEIGHT = 360
FPS = 60
DEV_MODE = os.getenv("DOOM_DEV_MODE", "").strip().lower() in {"1", "true", "yes", "on"}

FOV = math.radians(70)
MOVE_SPEED = 4.2
TURN_SPEED = math.radians(115)
MOUSE_SENSITIVITY = 0.0026
PLAYER_RADIUS = 0.22
PICKUP_RADIUS = 0.55
LOOT_LOS_STEP = 0.08
LOOT_MIN_PLAYER_DISTANCE = 2.25
LOOT_MIN_SPACING = 1.15
LOOT_ROOM_EDGE_PADDING = 2
DOOR_THICKNESS = 0.14
DOOR_OPEN_SPEED = 1.8
DOOR_PASSABLE_PROGRESS = 0.82
DOOR_INTERACT_DISTANCE = 1.7
DOOR_INTERACT_HALF_ANGLE = math.radians(32)
DOOR_MIN_PLAYER_DISTANCE = 3.5
DOOR_MIN_SPACING = 2.1
EXIT_TRIGGER_RADIUS = 0.42
SHOT_COOLDOWN = 0.48
SHOT_ANIM_FPS = 18.0
SHOT_FLASH_DECAY = 4.8
MAX_STEP_HEIGHT = 1.0
ELEVATION_SMOOTH_SPEED = 7.5
CAMERA_ELEVATION_SCALE = 0.34
MAX_HEALTH = 100
MAX_ARMOR = 200
MAX_SHELLS = 99
PLAYER_DAMAGE_FLASH_TIME = 0.34
ENEMY_HIT_FLASH_TIME = 0.12
PLAYER_DEATH_RESET_TIME = 1.4
PLAYER_ARMOR_ABSORB = 0.35

MAP_WIDTH = 36
MAP_HEIGHT = 36
MAX_ROOMS = 12
MIN_PROGRESSION_ROOMS = 8
ROOM_MIN_SIZE = 4
ROOM_MAX_SIZE = 9
MAPGEN_MAX_ATTEMPTS = 192
MAX_SIDE_CONNECTIONS_PER_STAGE = 1
MAX_FLOOR_LEVEL = 3
ENEMY_MIN_PLAYER_DISTANCE = 4.5
ENEMY_MIN_SPACING = 1.1
ENEMY_CORPSE_TIME = 3.5
ENEMY_THINK_INTERVAL = 0.16
ENEMY_SEPARATION_PUSH = 0.16
ENEMY_HEARING_RADIUS = 8.0
ENEMY_GUNSHOT_NOISE_TIME = 0.85
ENEMY_GUNSHOT_NOISE_RADIUS = 14.0
ENEMY_PROJECTILE_TIMEOUT = 4.8
ENEMY_PROJECTILE_PLAYER_HIT_RADIUS = 0.34
ENEMY_PROJECTILE_WALL_RADIUS = 0.08
ENEMY_DIFFICULTY_MIN = 0.82
ENEMY_DIFFICULTY_MAX = 1.28
ENEMY_DIFFICULTY_HEALTH_WEIGHT = 0.34
ENEMY_DIFFICULTY_ARMOR_WEIGHT = 0.28
ENEMY_DIFFICULTY_AMMO_WEIGHT = 0.18

BACKGROUND_TOP = (18, 20, 36)
BACKGROUND_BOTTOM = (70, 32, 16)
CEILING_COLOR = (36, 39, 61)
FLOOR_COLOR = (55, 31, 21)
ACCENT_COLOR = (239, 201, 126)
HUD_BG = (20, 12, 10)

MINIMAP_SCALE = 8
MINIMAP_MARGIN = 18
HUD_HEIGHT = 128

RAYCAST_STRIDE = 1
MAX_RAY_DISTANCE = 32.0
TEXTURE_SIZE = 64
FLOORCAST_STRIDE = 2
